version: 1.0.{build}
configuration:
- Debug
- Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: Withings.NET\bin
  name: Withings.NET
deploy: off